name: Deploy Backend to heroku.

# Run workflow on every push to main branch.
on:
  push:
    branches: ["main"]

# Your workflow jobs
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        users: actions/checkout@v2
